const rawFonts = [
  'Abel',
  'Abril Fatface',
  'Acme',
  'Alegreya',
  'Alegreya Sans',
  'Anton',
  'Archivo',
  'Archivo Black',
  'Archivo Narrow',
  'Arimo',
  'Arvo',
  'Asap',
  'Asap Condensed',
  'Bitter',
  'Bowlby One SC',
  'Bree Serif',
  'Cabin',
  'Cairo',
  'Catamaran',
  'Crete Round',
  'Crimson Text',
  'Cuprum',
  'Dancing Script',
  'Dosis',
  'Droid Sans',
  'Droid Serif',
  'EB Garamond',
  'Exo',
  'Exo 2',
  'Faustina',
  'Fira Sans',
  'Fjalla One',
  'Francois One',
  'Gloria Hallelujah',
  'Hind',
  'Inconsolata',
  'Indie Flower',
  'Josefin Sans',
  'Julee',
  'Karla',
  'Lato',
  'Libre Baskerville',
  'Libre Franklin',
  'Lobster',
  'Lora',
  'Mada',
  'Manuale',
  'Maven Pro',
  'Merriweather',
  'Merriweather Sans',
  'Montserrat',
  'Montserrat Subrayada',
  'Mukta Vaani',
  'Muli',
  'Noto Sans',
  'Noto Serif',
  'Nunito',
  'Open Sans',
  'Open Sans Condensed',
  'Oswald',
  'Oxygen',
  'PT Sans',
  'PT Sans Caption',
  'PT Sans Narrow',
  'PT Serif',
  'Pacifico',
  'Passion One',
  'Pathway Gothic One',
  'Play',
  'Playfair Display',
  'Poppins',
  'Questrial',
  'Quicksand',
  'Raleway',
  'Roboto',
  'Roboto Condensed',
  'Roboto Mono',
  'Roboto Slab',
  'Ropa Sans',
  'Rubik',
  'Saira',
  'Saira Condensed',
  'Saira Extra Condensed',
  'Saira Semi Condensed',
  'Sedgwick Ave',
  'Sedgwick Ave Display',
  'Shadows Into Light',
  'Signika',
  'Slabo 27px',
  'Source Code Pro',
  'Source Sans Pro',
  'Spectral',
  'Titillium Web',
  'Ubuntu',
  'Ubuntu Condensed',
  'Varela Round',
  'Vollkorn',
  'Work Sans',
  'Yanone Kaffeesatz',
  'Zilla Slab',
  'Zilla Slab Highlight'
];

export const fonts = [...new Set(rawFonts.map((font) => font.trim()).filter(Boolean))];
